title: LeaYw Blog
author: LeaYw
email: liyawei8696@163.com
description: > # this means to ignore newlines until "baseurl:"
  note for codding
# baseurl: "/minima"
# twitter_username: jekyllrb
github_username:  LeaYw

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
